crazy-mode is a Rube Goldberg machine mode for GNU Emacs.  crazy-mode helps you
code/go crazy.  Currently good support for C programming is included.

crazy-mode requires ~electric-pair-mode~ to work.

Source Repository: [[https://gitlab.com/sadiq/crazy-mode][GitLab]], [[https://github.com/pksadiq/crazy-mode][GitHub]]

Issues and Feature Requests: [[https://gitlab.com/sadiq/crazy-mode/-/issues][GitLab]]

Homepage: [[https://www.sadiqpk.org/projects/crazy-mode.html][https://www.sadiqpk.org/projects/crazy-mode.html]]

* Introduction
  crazy-mode hacks around the characters you type to do various stuff often
  reducing the effort to accomplish something.

  Say for example, in c-mode, pressing space bar often inserts '_' or sometimes
  real spaces depending on the context. It also inserts '-' when inside #include
  header names.

** C hacks
   '|' is the cursor point
   - pressing '.'
     - .. => (|)
     - #include.. => #include <|>
     - #include <.> => #include "|"
   - pressing space bar
     - _| => ->| (ie, pressing space bar twice gives ->)
     - #include <example|> => #include <example-|>
     - gtk| => gtk_|
     - difftime(time(NULL, |)) => difftime(time(NULL), |)
   - ' key
     - gtk_window| => GTK_WINDOW|
     - GTK_WINDOW| => GtkWindow|

* But why?
  Why not? This is GNU Emacs, anything is possible ;).

  I have been using this for around a decade in my personal config, and I decided
  to create a mode doing the same.

  And it's great to have something cool to show off about your editor, right?

* Recommended configuration

  #+BEGIN_SRC emacs-lisp
  ;; set custom path if loading from custom path
  ;; (add-to-list 'load-path "~/.emacs.d/crazy-mode/")
  (require 'crazy)
  (add-hook 'c-mode-common-hook
     (lambda ()
            (add-to-list 'c-cleanup-list 'space-before-funcall)
            (c-toggle-auto-newline 1)
            (electric-pair-mode 1)
            (crazy-mode 1)))
  #+END_SRC
